import { TECHNOLOGIES, TECHNOLOGIES_MAP } from '../data/research';
import type { Technology } from '../data/research';
import type { GameState } from '../game/GameState';

/** Base research points generated per research_center level per second. */
const BASE_RP_PER_SECOND = 1;

/**
 * Advances the active research by the research points generated this tick.
 * Completes research when accumulated points reach the technology's requirement.
 */
export function tick(state: GameState, deltaSeconds: number): void {
  if (!state.activeResearch) return;

  const technology = TECHNOLOGIES_MAP[state.activeResearch.technologyId];
  if (!technology) return;

  // Count research points generated by research centers this tick
  const rpThisTick = calcResearchPointsPerSecond(state) * deltaSeconds;
  state.activeResearch.progress += rpThisTick;

  if (state.activeResearch.progress >= technology.researchPoints) {
    completeResearch(state, technology);
  }
}

/**
 * Starts researching a technology. Deducts the money cost immediately.
 * Returns false if prerequisites are not met, already researched, already in
 * progress, or cash is insufficient.
 */
export function startResearch(state: GameState, technologyId: string): boolean {
  if (state.activeResearch) return false;
  if (isUnlocked(state, technologyId)) return false;

  const technology = TECHNOLOGIES_MAP[technologyId];
  if (!technology) return false;

  // Check prerequisites
  for (const prereq of technology.prerequisites) {
    if (!state.completedResearch.includes(prereq)) return false;
  }

  if (state.cash < technology.moneyCost) return false;

  state.cash -= technology.moneyCost;
  state.activeResearch = {
    technologyId,
    progress: 0,
    startedAt: state.tick,
  };
  return true;
}

/** Cancels the current research in progress. The money cost is not refunded. */
export function cancelResearch(state: GameState): void {
  state.activeResearch = null;
}

/** Returns true if a technology has been completed. */
export function isUnlocked(state: GameState, technologyId: string): boolean {
  return state.completedResearch.includes(technologyId);
}

/**
 * Returns technologies whose prerequisites are all met and that have not yet
 * been researched.
 */
export function getAvailableTechnologies(state: GameState): Technology[] {
  return TECHNOLOGIES.filter((t) => {
    if (isUnlocked(state, t.id)) return false;
    return t.prerequisites.every((p) => state.completedResearch.includes(p));
  });
}

/**
 * Returns 0-1 progress through the current research, or 0 if idle.
 */
export function getResearchProgress(state: GameState): number {
  if (!state.activeResearch) return 0;
  const technology = TECHNOLOGIES_MAP[state.activeResearch.technologyId];
  if (!technology || technology.researchPoints === 0) return 0;
  return Math.min(1, state.activeResearch.progress / technology.researchPoints);
}

/**
 * Applies any side-effects triggered when a technology completes, such as
 * generating an in-game alert listing what was unlocked.
 */
export function applyUnlocks(state: GameState, technology: Technology): void {
  const unlockNames = technology.unlocks.map((u) => `${u.type}:${u.id}`).join(', ');
  state.alerts.push({
    id: crypto.randomUUID(),
    tick: state.tick,
    type: 'success',
    messageKey: 'alerts.research_complete',
    params: [technology.nameKey, unlockNames],
  });
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function calcResearchPointsPerSecond(state: GameState): number {
  return state.buildings
    .filter((b) => b.typeId === 'research_center' && b.isPowered)
    .reduce((sum, b) => sum + BASE_RP_PER_SECOND * b.level, 0);
}

function completeResearch(state: GameState, technology: Technology): void {
  state.completedResearch.push(technology.id);
  applyUnlocks(state, technology);
  state.activeResearch = null;
}
